### ISSUE TITLE
Test "conservative" recursive copy

### ISSUE THREAD

**Issue by dralley** [PulpQE/Pulp-2-Tests#152]
Normal recursive copy will copy all dependencies to the target repo if versions of those dependencies are newer than in the target repo.

"Conservative" recursive copy will perform depsolving to determine whether the dependency is satisfied in the target repository, and if so, will not copy the newer deps.

See the linked issue for a more concrete example.

Additionally, this flag should NOT affect copies of modular content, only copies of non-modular content.  All dependencies of modular content should always be copied, just like a normal recursive copy, even if this flag is specified.

https://pulp.plan.io/issues/2478
https://github.com/pulp/pulp_rpm/commit/cb4d33c5f998b91b3b42ec551db21d22139dde63

**Comment by goosemania** [comment]
> Normal recursive copy does not check whether dependencies of packages being copied are satisfied by packages present in the target repository, it will just copy all versions of the dependencies to the target repo.

How about something like this (to be more precise):
Normal recursive copy will copy all dependencies to the target repo if versions of those dependencies are newer than in the target repo.

**Comment by kersommoura** [comment]
Tests were added to this issue:

See: https://github.com/PulpQE/Pulp-2-Tests/pull/156

**Comment by kersommoura** [comment]
See also: https://pulp.plan.io/issues/4269

**Comment by bherrin3** [comment]
Linked to the following to consume this work. 
Closing.

- https://pulp.plan.io/issues/4269
- https://pulp.plan.io/issues/4543
