### ISSUE TITLE
Test puppet modules with extraneous files

### ISSUE THREAD

**Issue by rochacbruno** [PulpQE/Pulp-2-Tests#83]
> Migrated from https://github.com/PulpQE/pulp-smash/issues/627
> author: @daviddavis - https://github.com/daviddavis
> date created: 2017-04-27T22:06:56Z

See this issue for a list of potential puppet modules that could contain extraneous files:

https://pulp.plan.io/issues/1846

marcel-passenger-0.5.0.tar.gz is a good one.

When you extract one of these modules, it should contain something to the effect of:

```
-rwxr-xr-x   1  501 user  311 Mar 27  2015 ._marcel-passenger-0.5.0
drwxr-xr-x   7  501 user 4.0K Mar 27  2015 marcel-passenger-0.5.0
```

The `._marcel-passenger-0.5.0` file is a MacOS metadata file. It was causing our code to fail before.

### Steps

1. Create a puppet repo
2. Upload the puppet module to your repo
2. It should be successful

This original bug was a bit nondeterministic. Sometimes it occurred, sometimes it did not (depending on the order of the files listed by `os.listdir()`). The fix should solve it though by ignoring the file.

**Comment by ragabala** [comment]
Hii @daviddavis,

I was trying to automate this issue as a part of pulp2 backlogs.
When I tried to do the following manually, I am not able to upload the above marcel-passenger package.

Here are the steps I followed
```bash
wget https://forge.puppet.com/v3/files/marcel-passenger-0.5.0.tar.gz
pulp-admin puppet repo create --repo-id marcelpuppet
pulp-admin puppet repo uploads upload --file marcel-passenger-0.5.0.tar.gz --repo-id marcelpuppet
pulp-admin puppet repo list
```
This above command failed, throwing the following 
> Task Failed
> Could not find metadata file inside Puppet module

I tried the same command with the puppetmodule in [pulp-fixtures](https://repos.fedorapeople.org/pulp/pulp/fixtures/puppet/) and that passed
```bash
wget https://repos.fedorapeople.org/pulp/pulp/fixtures/puppet/pulpqe-dummypuppet.tar.gz
pulp-admin puppet repo create --repo-id dummypuppet
# changing the name to include version in it.
mv pulpqe-dummypuppet.tar.gz pulpqe-dummypuppet-0.1.0.tar.gz 
pulp-admin puppet repo uploads upload --file pulpqe-dummypuppet-0.1.0.tar.gz --repo-id dummypuppet
pulp-admin puppet repo list
``` 

Can you let me know your thoughts on why the marcel-passenger package is not getting uploaded?

**Comment by ragabala** [comment]
Thanks @daviddavis
