### ISSUE TITLE
Test Pipe leak in any parent Pulp celery process triggered by qpidd restart

### ISSUE THREAD

**Issue by rochacbruno** [PulpQE/Pulp-2-Tests#85]
> Migrated from https://github.com/PulpQE/pulp-smash/issues/551
> author: @preethit - https://github.com/preethit
> date created: 2017-02-10T17:40:05Z

https://pulp.plan.io/issues/2582

The issue has a detailed reproducer. @Ichimonji10 could you please take a look to see if this can be automated.

**Comment by rochacbruno** [comment]
> Migrated from https://github.com/PulpQE/pulp-smash/issues/551#issuecomment-279039475
> author: @Ichimonji10 - https://github.com/Ichimonji10
> date created: 2017-02-10T19:18:52Z

I *think* this can be automated. If we can find some good, reliable way of finding the pid of a processes' parent, then for sure, it can be automated.

**Comment by kersommoura** [comment]
The related issue https://pulp.plan.io/issues/2582 was manually tested using celery 4. Besides that, this one was a better fit for manual testing.
