### ISSUE TITLE
Assert then YumMetadataFile copy save its new storage_path.

### ISSUE THREAD

**Issue by rochacbruno** [PulpQE/Pulp-2-Tests#91]
> Migrated from https://github.com/PulpQE/pulp-smash/issues/279
> author: @ipanova - https://github.com/ipanova
> date created: 2016-05-31T15:43:31Z

1. create  repo A
2. sync from a feed or upload yum_metadata_file
3. create repo B
4. copy yum_metadata_file from repo A to B
5. publish repo B
6. remove yum_metadata_file from repo A
7. remove orphans
8. publish repo B again ---> publish should succeed

for more info check https://pulp.plan.io/issues/1944
https://pulp.plan.io/issues/1935#note-5
https://github.com/pulp/pulp_rpm/pull/895

**Comment by ragabala** [comment]
@ipanova

Is there any existing feed with this yum_metadata_file??

**Comment by ragabala** [comment]
@ipanova Thanks Ina.

Can you let me know if you can point me to any of the resources that have these repodata files that can be used for adding the testcase?

**Comment by ipanova** [comment]
@ragabala it is in Rhel repo, for example.

**Comment by ragabala** [comment]
Closing this one out, Since we have no Fixtures to test this.

**Comment by ipanova** [comment]
@ragabala  what prevents us to create fixtures or test from rhel repo? :)
we had a lot of bugs around this issue.

**Comment by ragabala** [comment]
HI @ipanova,

Thanks, I wasn't aware of it. Apologize for closing this one out. Since there isn't a fixture already existing @kersommoura  and myself decided to move with the other backlog issues. Also, I don't see any of our tests pointing to Rhel Repos.
